version: '3'

services:
  rabbitmq_a:
    build:
      context: rabbitmq
    volumes:
      - ./.data/rabbitmq_a:/var/lib/rabbitmq
    hostname: rabbitmq_a
    command: /start.sh

  rabbitmq_b:
    build:
      context: rabbitmq
    volumes:
      - ./.data/rabbitmq_b:/var/lib/rabbitmq
    hostname: rabbitmq_b
    command: /start.sh

  consumer:
    build:
      context: python
    volumes:
      - ../../:/source
      - .data/consumer/:/data
    working_dir: /source/consumer
    env_file:
      - .envs/application.env
    environment:
      - RUN_COMMAND=/source/consumer/run.sh
    command: run_dramatiq

  sender:
    build:
      context: python
    volumes:
      - ../../:/source
      - .data/sender/:/data
    working_dir: /source/sender
    env_file:
      - .envs/application.env
    environment:
      - RUN_COMMAND=/source/sender/run.sh
    command: run_flask
